#!/usr/bin/env python3

import os
import threading
from adafruit_servokit import ServoKit

pca = ServoKit(channels=16)

def servoMove(servo,angle):
    pca.servo[int(servo)].angle=int(angle)


try:

    s1 = threading.Thread(target=servoMove, args=(1,90))
    s2 = threading.Thread(target=servoMove, args=(5,90))
    s3 = threading.Thread(target=servoMove, args=(9,90))
    s4 = threading.Thread(target=servoMove, args=(13,90))
    s1.start()
    s2.start()
    s3.start()
    s4.start()

except:
    print("[x] An exception has ocurred" )

print("[!] Exit ...")
exit(0)
